### ISSUE TITLE
Any chance this will work on Kodi 19 Matrix?

### ISSUE THREAD

**Issue by Cookie-Monster-Coder** [AchillesPunks/repository.bingie.mod#12]
Love the Skin on Kodi 18 and would love to see it ported to Kodi v19.

**Comment by AchillesPunks** [comment]
In the process right now. I have it running on Matrix as we speak. I'm just fixing a few more issues.

**Comment by AchillesPunks** [comment]
Yes I'm almost done with the matrix version as we speak.

**Comment by Pfuenzle** [comment]
Hi there, any updates on support for version 19?

**Comment by AchillesPunks** [comment]
The skin already works on Kodi 19
