### ISSUE TITLE
[Enhancement] improve red circle details

### ISSUE THREAD

**Issue by georgew21** [AchillesPunks/repository.bingie.mod#9]
Hello and congrats for the great skin!

on bingie view on library or on widgets, we have under  the plot, red circles icons that show info about genre/director/actros which change after some sec.

could have the option to show in two rows permanently director and genre info? 

these are the 2 most important info and we have to wait a lot to see the director of the movie or the genre, because they aren't showing simutalenusly.

taking granted that there is a lot space, it could be useufull to show genres and the director permanently, without changing.

**Comment by AchillesPunks** [comment]
I don't have the time right now to add the code
